### ISSUE TITLE
Problem with "Timer enable Dim" not Restore to previous state

### ISSUE THREAD

**Issue by orda1** [ketra/nl.ketra.devicetimer#14]
**Describe the bug**
Love the App :)
Timer enable Dim: Not restore to previous state when sensor detect moment in timer period.  

**To Reproduce**
Making Flow
1. When: Fibaro Multi sensor - FGMS-001-PLUS (the motion alarm turned on)
2. Then: Fibaro Dimmer 2 - FGD-212 - (Timer enable Dim: 10sec, Control it anyway, set the timer/keep the running timer, Restore to previous state. 

Fibaro dimmer is sett to 10% and the Fibaro Multi sensor is off. When i walk in the room motion detektor is activated the fibaro dimmer up to 50% and i walk out off the room before the timer (10sec) running out. The dimmer goes to 10%. Everything work perfect.
The same as above, but now i´m in the room more then 10 sek (the motion sensor goes on/off repeatedly) when i leave the room the fibaro dimmer turn off not to 10%

**Expected behavior**
The fibaro dimmer goes to previous state every time.

**Screenshots**
<img width="1271" alt="skjermbilde 2018-12-12 kl 17 33 54" src="https://user-images.githubusercontent.com/45826203/49884009-29edb980-fe34-11e8-85a0-aa327add5c25.png">

<img width="735" alt="skjermbilde 2018-12-12 kl 17 35 56" src="https://user-images.githubusercontent.com/45826203/49884118-691c0a80-fe34-11e8-825d-4461b3bd5961.png">

**Additional context**

**Comment by ketra** [comment]
this seems like the app timers. not devicetimer since my app does not use flows
https://github.com/lvanderree/com.synplyworks.thenmore/issues
